name: Bandit Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Bandit 1.7.5
        run: pip install bandit==1.7.5

      - name: Run Bandit Security Scan
        run: bandit -r . -f json -o results.json --exit-zero

      - name: Verify json
        run: |
            ls 
            cat results.json

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: results.json

      - name: Send Report to Challenge Listener
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" \
          -F "file=@results.json" http://35.219.161.29:8880/callback